### ISSUE TITLE
Can't migrate to annotations

### ISSUE THREAD

**Issue by AndrewBryukhov** [Silvmike/spring-integration-wildfly-queue#1]
Hello how to migrate this great source code to annotations?

**Comment by Silvmike** [comment]
You can have a look at:
https://github.com/spring-projects/spring-integration-java-dsl/wiki/spring-integration-java-dsl-reference
https://spring.io/blog/2014/11/25/spring-integration-java-dsl-line-by-line-tutorial

If you have a specific problem, let me know :)

P.S. or you can just wait, I'll add java-dsl test this weekend.
