### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by AndrewBryukhov** [Silvmike/spring-integration-wildfly-queue#2]
After running "maven test" i see message in wildfly

> INFO  [class ejb3.HelloWorldQueueMDB] (Thread-5 (ActiveMQ-client-global-threads-933071506)) Received Message from queue: Hello TestQueue

But also i got this exception on conole:

> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> Running ru.hardcoders.QueueJavaDslTest
> 00:04:54,795 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
> 00:04:54,795 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
> 00:04:54,795 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/D:/main/Tests/spring-integration-wildfly-queue-master/target/test-classes/logback.xml]
> 00:04:54,861 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
> 00:04:54,874 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
> 00:04:54,883 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [App]
> 00:04:54,905 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
> 00:04:54,968 |-INFO in ch.qos.logback.core.FileAppender[App] - File property is set to [application.log]
> 00:04:54,970 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
> 00:04:54,971 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
> 00:04:54,979 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
> 00:04:54,979 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
> 00:04:54,979 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
> 00:04:54,980 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ru.hardcoders.readRoute] to DEBUG
> 00:04:54,980 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [App] to Logger[ru.hardcoders.readRoute]
> 00:04:54,981 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
> 00:04:54,981 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
> 00:04:54,981 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
> 00:04:54,982 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@64bfbc86 - Registering current configuration as safe fallback point
> 
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.055 sec <<< FAILURE!
> test(ru.hardcoders.QueueJavaDslTest)  Time elapsed: 10.563 sec  <<< FAILURE!
> Wanted but not invoked:
> messageChannel.send(<any>);
> -> at ru.hardcoders.AbstractQueueTest.test(AbstractQueueTest.java:39)
> Actually, there were zero interactions with this mock.
> 
> 	at ru.hardcoders.AbstractQueueTest.test(AbstractQueueTest.java:39)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
> 	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
> 	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
> 	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
> 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
> 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
> 
> 
> Results :
> 
> Failed tests:   test(ru.hardcoders.QueueJavaDslTest): (..)
> 
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

Also i need to use message listener:

```
        @Autowired
        MessageReceiver messageReceiver;

        //method 'getContainer' threw exception; nested exception is java.lang.IllegalArgumentException:
        // Message listener needs to be of type [javax.jms.MessageListener] or [org.springframework.jms.listener.SessionAwareMessageListener]

        @Bean
        public MessageListenerContainer getContainer(@Value("${queue}") String queueName,
                                                     @Autowired @Qualifier("targetCF") ConnectionFactory connectionFactory){
            DefaultMessageListenerContainer container = new DefaultMessageListenerContainer();
            container.setConnectionFactory(connectionFactory);
            container.setDestinationName(queueName);
            container.setMessageListener(messageReceiver);
            return container;
        }
...
@Component
public class MessageReceiver implements MessageListener {

	static final Logger LOG = LoggerFactory.getLogger(MessageReceiver.class);
	
	@Autowired
	MessageConverter messageConverter;
	
	
	@Override
	public void onMessage(Message message) {
		try {
			LOG.info("+++++++++++++++++++++++++++++++++++++++++++++++++++++");
			/*InventoryResponse*/Object response = /*(InventoryResponse)*/ messageConverter.fromMessage(message);
			LOG.info("Application : order response received : {}",response);	
			LOG.info("+++++++++++++++++++++++++++++++++++++++++++++++++++++");
		} catch (JMSException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
}
```

**Comment by Silvmike** [comment]
@AndrewBryukhov ,
this test will pass with success in the only one case: there is no other consumers. 
Seems you have an MDB consuming messaging from the same queue (stealing message from test consumer).
I don't see any problem with your code: it should work.
