### ISSUE TITLE
Suggestion for creating queue on wilfdly side

### ISSUE THREAD

**Issue by AndrewBryukhov** [Silvmike/spring-integration-wildfly-queue#3]
Hello thx for examples.
Want to see how to create queue on wildfly side by activemq createQueue() method.

**Comment by Silvmike** [comment]
What do you mean? Be more specific, please. 
If you want to know how to add queue using JBoss CLI, I'd recommend to start [here](goo.gl/gxi63i), look at [this repository](https://github.com/wildfly/quickstart/tree/11.x/helloworld-jms), and, of course, an official [documentation](https://docs.jboss.org/author/display/WFLY10/Java+Message+Service+API+(JMS)).

**Comment by AndrewBryukhov** [comment]
No cli, i mean creating queue programmaticly by method createQueue without any xml edit.

**Comment by Silvmike** [comment]
Ah, ok. ActiveMQ itself allows to do it, but I am not an expert in ActiveMQ in WildFly. There is an example [here](https://activemq.apache.org/artemis/docs/1.0.0/using-jms.html). It requires some research to answer, and has no connection to this repository.
